dataset:
  data_path: E:/research/my_code/solar_flow/data
  years:
    train:
    - 2017
    - 2018
    - 2019
    - 2020
    val:
    - 2021
    test:
    - 2022
  input_len: 8
  pred_len: 8
  stride: 1
  use_possible_starts: true
batch_size: 16
num_workers: 4
pin_memory: true
