
run:
  dir: ${work_dir}/logs/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
sweep:
  dir: ${work_dir}/logs/multiruns/${now:%Y-%m-%d_%H-%M-%S}
  subdir: ${hydra.job.num}

job:
  env_set:
    EXAMPLE_VAR: "example_value"