model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val_loss" # name of the logged metric which determines when model is improving
  save_top_k: 1 # save k best models (determined by above metric)
  save_last: True # additionaly always save model from last epoch
  save_weights_only: True # Save only weights and hyperparams, makes smaller and doesn't include callbacks/optimizer/etc. Generally, this should be True, as haven't really been restarting training runs much
  mode: "min" # can be "max" or "min"
  verbose: False
  dirpath: ${paths.ckpt_dir}
  filename: "{epoch:03d}-{val_loss:.4f}"

# early_stopping:
#  _target_: pytorch_lightning.callbacks.EarlyStopping
#  monitor: "val_loss" # name of the logged metric which determines when model is improving
#  patience: 10 # how many epochs of not improving until training stops
#  mode: "min" # can be "max" or "min"
#  min_delta: 1e-4 # minimum change in the monitored metric needed to qualify as an improvement
rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar

model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: 2